services:
  aurora:
    image: 'ghcr.io/quantinium3/aurora'
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_POSTGRES_HOST: "postgres"
      DB_POSTGRES_PORT: "5432"
      DB_POSTGRES_USER: "postgres"
      DB_POSTGRES_PASSWORD_FILE: /run/secrets/postgres_pwd
      DB_POSTGRES_NAME: "aurora"
    ports:
      - 4000:4000
    networks:
      - alice
    depends_on:
      migrate:
        condition: service_completed_successfully

  migrate:
    image: 'ghcr.io/quantinium3/drizzle-migrate'
    env_file:
      - .env
    networks:
      - alice

networks:
  alice:
    external: true
    name: alice
