name: VPS CICD

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace image tag with commit SHA
        run: |
          sed -i "s|:latest|:sha-${{ github.event.workflow_run.head_sha }}|" docker-compose.yml

      - name: copy docker-compose.yml to vps
        uses: appleboy/scp-action@v1
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          source: "docker-compose.yml"
          target: "/home/natsuki/aurora"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io --username "${{ github.actor }}" --password-stdin

            docker compose -f /home/natsuki/aurora/docker-compose.yml pull
            docker compose -f /home/natsuki/aurora/docker-compose.yml up -d

            docker image prune -f
